= CloudHub
:keywords: cloudhub, cloud, api, runtime manager, arm


link:http://www.mulesoft.com/cloudhub/ipaas-cloud-based-integration-demand[CloudHub] is an integration platform as a service (iPaaS). Through the link:/runtime-manager/[Anypoint Runtime Manager], it allows you to deploy sophisticated cross-cloud integration applications in the cloud, create new APIs on top of existing data sources, integrate on premises applications with cloud services, and much more. This guide helps you learn the basics, and get started developing your first application.

This page deals with some basic concepts about CloudHub. After this short overview, you can build your first CloudHub integration with the link:/runtime-manager/hello-world-on-cloudhub[Hello World on CloudHub] tutorial.

[TIP]
Through the same link:/runtime-manager/[Runtime Manager] console that you deploy applications to CloudHub, you can also link:/runtime-manager/deploying-to-your-own-servers[deploy] to link:/runtime-manager/managing-servers[servers, server groups and clusters] on-premises.

== Benefits of CloudHub

=== Easy Scalability

CloudHub is an elastic cloud that scales on demand. You can start small and grow as your needs grow, all without changing your application. CloudHub provides you with a scalable architecture – one you can build integration applications on, publish REST APIs or Web Services, and much more. You can also manage servers in your organization from CloudHub and organize servers into groups that run an application.

////
you can also do autoscaling!!!!
////

=== Easy Transition Between Cloud and On-Premise Deployments

Create CloudHub applications with the development tools you are already familiar with. Download link:https://www.mulesoft.com/ty/dl/studio[Anypoint Studio], it's free! Anypoint Studio is an Eclipse-based graphical environment that allows developers to easily choose to code in a visual environment with a palette of components, or in a familiar XML code view. You can even switch between the visual and code views as you build your application. Or, if you would rather use the command-line, we support Maven, as a command line tool.


You can deploy the same Mule applications interchangeably both to CloudHub or to an link:/runtime-manager/deploying-to-your-own-servers[on premise server]. Keep in mind that there are link:/runtime-manager/cloudhub-and-mule[some considerations] to take into account about how some features work between both kinds of environments.



cloudhub vs on prem,  list of features




=== Visibility and Control through the Anypoint Runtime Manager

With CloudHub, you also get our intuitive cloud console where you can manage your applications and servers, scale up and scale down, view event traffic, and much more. The Anypoint Runtime Manager allows you to manage every aspect of your CloudHub applications from one place. In addition, with link:/runtime-manager/managing-servers[server management] and link:/runtime-manager/managing-servers#create-a-cluster[cluster management] you can manage your on-premise servers, server groups, and clusters, plus applications from your CloudHub console, giving you a single management pane of glass for all your applications and servers.


From there you can link:/runtime-manager/managing-cloudhub-applications[manage running applications]. It also allows you to triage problems, view logs, set up alerts, view dashboards, and more. Follow the simple steps in the link:/runtime-manager/hello-world-on-cloudhub[Hello World] tutorial to setup your free Anypoint Platform account and deploy your first application to it.


[NOTE]
You can view the live status and detailed service history for the Runtime Manager console, platform services, and the CloudHub worker cloud on link:http://trust.mulesoft.com/[trust.mulesoft.com].

=== Integration with Anypoint Studio


CloudHub is built on top of Mule, the most widely used integration platform. With Anypoint Studio – the user-friendly development tool – you can quickly build these integration applications and deploy to CloudHub with just a few clicks, without even leaving Anypoint Studio, see link:.

Once your application is deployed to CloudHub's multi-tenant runtime, you can link:http://anypoint.mulesoft.com[log in] to the Anypoint Platform, and then go to the Runtime Manager. You'll see your application running and will be able to perform management tasks on it like any other application deployed through the platform.


=== Integrate Cloud and Enterprise Applications

The CloudHub link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud (VPC)] offering allows you to construct a secure pipe to the enterprise through an IPsec or SSL based VPN.



== Next Steps


=== Learn CloudHub Basics

* Download link:https://www.mulesoft.com/lp/dl/studio[Anypoint Studio].
* Follow our easy link:/runtime-manager/hello-world-on-cloudhub[Hello World on CloudHub] tutorial to get your first integration application up and running with Anypoint Studio and CloudHub.
* Ready to deploy an application?  See link:/runtime-manager/deploying-a-cloudhub-application[Deploying a CloudHub Application].
* Still don't understand how CloudHub can be of use to you? Read more about link:http://www.mulesoft.com/cloudhub/ipaas-cloud-based-integration-demand[things you can do with CloudHub].

=== Build CloudHub Applications

Follow one of our tutorials to learn how to build CloudHub applications.

* link:/runtime-manager/hello-world-on-cloudhub[Hello World on CloudHub]

* link:/runtime-manager/building-an-https-service[Building an HTTPS Service on CloudHub]  
* link:/runtime-manager/custom-application-alerts[Custom Application Alerts] 

Want to learn more? Check out all the examples in link:/mule-fundamentals/v/3.7/anypoint-exchange[Anypoint Exchange].

=== Deploy Applications to the Cloud or On Premises

The same Runtime Manager console enables you to deploy and manage applications both on CloudHub and on premises.

* link:/runtime-manager/deploying-to-cloudhub[Deploy Applications] to the cloud
* link:/runtime-manager/deploying-to-your-own-servers[Deploy Applications] to on premise servers
* link:/runtime-manager/managing-deployed-applications[Manage Deployed Applications] from the cloud console
* link:/runtime-manager/managing-cloudhub-applications[Manage CloudHub Applications] deals with settings specific to CloudHub
* link:/runtime-manager/managing-servers[Register on-premise servers] to be managed via the cloud platform (as individual servers, as server groups or as parts of a cluster)


=== CloudHub API

Do you need to automate tasks, or build CloudHub into your deployment process? CloudHub has a link:/runtime-manager/cloudhub-api[REST API] with which you can perform tasks such as manage and monitor your applications, scale your applications up or down, and more.


=== Other Resources

* link:/runtime-manager/deploying-to-cloudhub[Deploying to CloudHub]
* link:/runtime-manager/managing-deployed-applications[Managing Deployed Applications] 
* link:/runtime-manager/managing-cloudhub-applications[Managing CloudHub Applications] 
* link:/runtime-manager/cloudhub-faq[CloudHub FAQ]

* There are tons of APIs available. Check our MuleSoft Blog for a list of the link:http://blogs.mulesoft.org/top-10-weird-apis/[TOP 10 of the weirdest APIs] out there.

You can also obtain more information about CloudHub and Anypoint Studio here:

* link:/mule-fundamentals/v/3.7/elements-in-a-mule-flow[Elements in a Mule Flow]
