= Runtime Manager
:keywords: cloudhub, cloud, saas, applications, servers, clusters, sdg, runtime manager, arm

[NOTE]
====
The topics in this document deal with app deployments through both the cloud-based and the on-premise versions of the Runtime Manager console. It also deals with deployments to both CloudHub and on-premise environments. See link:/runtime-manager/cloudhub-and-runtime-manager[CloudHub and Runtime Manager] for a better understanding of the differences between both.
====


The Runtime Manager is the tool in the link:/mule-fundamentals/v/3.8-m1/anypoint-platform-primer[Anypoint Platform] with which you deploy and centrally manage all of your link:/mule-fundamentals/v/3.8-m1/begin-with-the-basics[Mule applications], whether they are running in the cloud or on-premises.

After you've link:/mule-fundamentals/v/3.8-m1/build-a-hello-world-application[created a Mule application] (be it through Anypoint Studio or outside), you can deploy it so that it runs either in CloudHub – our cloud IPaaS platform – or on one of your own servers, server groups, or clusters.

It provides a dashboard that indicates the status of every deployed app and every monitored server, as well as a rich set of features that allow you to manage and track activity on the applications that are already running.


* link:/runtime-manager/cloudhub-and-runtime-manager[CloudHub and Runtime Manager]
* link:/runtime-manager/deploying-to-cloudhub[Deploying to CloudHub]
* link:/runtime-manager/deploying-to-your-own-servers[Deploying to Your Own Servers]
* link:/runtime-manager/managing-deployed-applications[Managing Deployed Applications]
* link:/runtime-manager/managing-servers[Managing Servers]
* link:/runtime-manager/cloudhub[CloudHub]

== Context

After software developer teams create Mule applications using Anypoint Studio (or another IDE), they typically pass the Mule application to another team who deploys the application in a simulated environment for more rigorous testing. Afterwards, the application is run in production with strict requirements to be constantly available, performing at a certain rate, and continually working as expected. On Anypoint Studio, hitting the *Play* button deploys your application to a test server that is built into Studio, this server has limitations and is not meant for production deployments. Ultimately you will want to deploy your application to either CloudHub or to a Mule Runtime instance running on a server, both of which are managed via the Runtime Manager.

The Runtime Manager is an enterprise management and monitoring tool designed specifically for Mule runtime instances. The Runtime Manager provides a comprehensive set of functionality for managing and monitoring running Mule instances, CloudHub workers, Mule clusters, applications within Mule instances, and the flows within those applications.

The Runtime Manager provides a centralized, convenient, and intuitive web-based interface to monitor, manage, and administer the run-time aspects of Mule runtimes. It also provides a downloadable version that runs entirely on-premises, which allows you to keep all of your infrastructure secure under your required policies.

[TIP]
For managing apps on your own servers, you can still resort to the link:m/mule-management-console/v/3.7/index[Mule Management Console] as an alternative to the Runtime Manager. This older tool is no longer being developed, but has some features that are currently not yet implemented in the Runtime Manager for on-premise scenarios.

== See Also

For a basic introduction into what a Mule Application is and how to create one, see:

* link:/mule-fundamentals/v/3.8-m1/anypoint-platform-primer[Anypoint Platform]
* link:/mule-fundamentals/v/3.8-m1/begin-with-the-basics[Mule applications]
* link:/mule-fundamentals/v/3.8-m1/elements-in-a-mule-flow[Elements in a Mule Flow]
* link:/mule-fundamentals/v/3.8-m1/build-a-hello-world-application[created a Mule application]
