= Managing Applications On Your Own Servers
:keywords: cloudhub, managing, monitoring, deploy, runtime manager, arm

After you have link:/runtime-manager/managing-servers#add-a-server[added a server] and link:link:/runtime-manager/deploying-to-your-own-servers[deployed an application] to it, you can use the Runtime Manager to monitor and manage your application.

Depending on if your application is deployed to link:/runtime-manager/deploying-to-cloudhub[CloudHub] or to link:/runtime-manager/deploying-to-your-own-servers[your own servers], there is a different set of possible actions you can perform on it, once deployed. This page focuses on the actions that are specific to applications deployed to your own servers, wether on the cloud or on premises. To view the basic management tools that are common to both types of deployment targets, see link:/runtime-manager/managing-deployed-applications[Managing Deployed Applications].

With applications deployed to link:/runtime-manager/managing-applications-on-your-own-servers[your own servers] you can do the following:

* link:/runtime-manager/sending-data-from-arm-to-external-monitoring-software[Sending Data from Runtime Manager to External Monitoring Software]
* link:/runtime-manager/managing-servers[Manage Servers]
* link:/runtime-manager/creating-and-managing-clusters[Create clusters and server groups]

[TIP]
Wether you're using the link:anypoint.mulesoft.com[cloud based] or the link:/anypoint-on-premises/[on premise edition] of the Anypoint Platform, or even the standalone link:/anypoint-on-premises/[on premise edition] of the Runtime Manager, features described in this page work identically in all of them.

== See Also

Additional tools for managing your applications:

* link:/runtime-manager/cloudhub-console-overview[CloudHub Console Overview]
* link:/runtime-manager/managing-servers[Managing Servers]
* link:/runtime-manager/cloudhub-administration[CloudHub Administration]
* link:/runtime-manager/alerts-and-notifications[Alerts and Notifications]
* link:/runtime-manager/cloudhub-fabric[CloudHub Fabric]
* link:/runtime-manager/cloudhub-insight[CloudHub Insight]
* link:/runtime-manager/managing-queues[Managing Queues]
* link:/runtime-manager/managing-schedules[Managing Schedules]
* link:/runtime-manager/managing-application-data-with-object-stores[Managing Application Data with Object Stores]
* link:/runtime-manager/command-line-tools[Command Line Tools]
* link:/runtime-manager/secure-application-properties[Secure Application Properties]
* link:/runtime-manager/viewing-log-data[Viewing Log Data]
* link:/runtime-manager/virtual-private-cloud[Virtual Private Cloud]
* link:/runtime-manager/worker-monitoring[Worker Monitoring]
* link:/runtime-manager/penetration-testing-policies[Penetration Testing Policies]
* link:/runtime-manager/secure-data-gateway[Secure Data Gateway]

 
