= Command Line Interface Shell for Anypoint Platform.
:keywords: administration, api, organization, users, gateway, theme, cli

Anypoint Platform provides you a command line tool to interact with your applications through both interactive shell and standard CLI modes.

== Assumptions

This document assumes that you are familiar with our link:/anypoint-platform-for-apis/anypoint-platform-for-apis-walkthrough[Anypoint platform for APIs walkthrough] and that you are able to link:/anypoint-platform-for-apis/managing-your-api[manage your API using Anypoint Platform].

////
== Installation

[IMPORTANT]
First you need to make sure you have the node.js runtime environment installed in your machine. Along with it, you'll need to use node's default package manager (npm) to be able to install Anypoint-CLI.
Following the steps in the link:https://docs.npmjs.com/getting-started/installing-node[node documentation] will help you get both resources.

You can install Anypoint-CLI using node's default package manager by typing in your console

[source,bash]
----
$ npm install -g anypoint-cli
----
////

== Usage
Every instance of Anypoint-CLI takes any of the following parameters:

[width="100a",cols="33a,33a,33a",options="header"]
|===
|Parameter |Description| Required
|username | Your Anypoint Platform username. +
You can also use an environment variable (e.g. `export ANYPOINT_USERNAME=<name>`)| *Yes*
|password | Your Anypoint Platform password. +
You can also use an environment variable (e.g. `export ANYPOINT_PASSWORD=<pwd>`)| *Yes*
|organization| Your organization within Anypoint Platform. +
You can also use an environment variable (e.g. `export ANYPOINT_ORG=<name>`)| No
|environment| Your Anypoint-CLI environment. +
You can also use an environment variable (e.g. `export ANYPOINT_ENV=<name>`)| No
|===

[IMPORTANT]
--
A few considerations to keep in mind while using Anypoint-CLI:

. As instructed above, the username and password parameters are required. If you don't pass them, Anypoint-CLI will not run. For security reasons we strongly recommend to pass both parameters as environment variables, such as the example above `$ANYPOINT_USERNAME` and `$ANYPOINT_PASSWORD` +
. If you don't set an environment, you will be automatically sent to `production`. +
. Your Anypoint session won't expire if you are accessing through this command line interface. +
. Anypoint-CLI works with autocomplete. You can start typing the name of the command or parameter and hit `tab` for an autocomplete, or double tap `tab` for a list of all possible options.
--

Once you have your parameters in order, you can pass commands. +
A list of available commands is below:

[width="100a",cols="50a,50a",options="header"]
|===
|Command |Description
|<<exit>> |  Exits anypoint-cli
|<<account>> |  Show account details
|<<business-groups>> |Lists business groups
|<<business-groups show>> |Show details of abusiness group
|<<business-groups use>> | Make specifiedbusiness-group active
|<<apps>> |  Lists all applications in the environment
|<<apps show>> |  Show application details
|<<apps json>> |  Show raw application JSONresponse
|<<apps stop>> |  Stop a runningapplication
|<<apps start>> | Start an application
|<<apps restart>> |  Restart a runningapplication
|<<apps delete>> |Delete an application
|<<apps deploy>> | Deploy a new application
|<<apps update>> | Update an existingapplication, optionallyupdating the zip file
|<<apps revert>> |Reverts application to its previous runtime environment
|<<apps tail>> |  Tail application logs
|<<apps download-logs>> |  Download application logsto specified directory
|<<environments>> |Lists environments
|<<environments use>> | Make specifiedenvironment active
|<<environments create>> |Create new environment
|<<environments delete>> | Delete an environment
|<<lbs>> |Lists all load balancers
|<<lbs show-rules>> |Lists the proxy rules for a load balancer
|<<lbs add-rule>> | Adds a rule at thespecified index.
|<<lbs delete-rule>> |Delete a rule at thespecified index.
|<<lbs create>> |  Creates a load balancer
|<<lbs update>> |Updates a load balancer
|<<lbs delete>> | Delete a load balancer
|<<regions>> |  Lists all supportedregions
|<<runtimes>> | Lists all supported runtimes
|<<token>> | Show API access token
|<<vpcs>> |  Lists all VPCs
|===

An Anypoint-CLI call should then have the following form:
[source,bash]
----
$ anypoint-cli [params] [command]
----

If you choose not to pass a command, Anypoint-CLI will run in *interactive mode*.
If you choose to pass a specific command and there is an error, the application will exit and return you a description of the issue.

== List of commands

[TIP]
Use the `--help` option with a command to see what options are available.

=== account
[source,bash]
----
$ account [options]
----

This command simply returns the information for your account. This includes your username, your full name, your email address, and creation of your account. +
This command does not take any options, except for the default `--help`

=== business-groups
[source,bash]
----
$ business-groups [options]
----

This command displays all link:/anypoint-platform-administration/manage-your-organization-and-business-groups[business-groups]. It returns return the name of the business group, the type ('Master' or 'Business unit') and the Id. +
This command does not take any options, except for the default `--help`.


=== business-groups show
[source,bash]
----
$ business-groups show [options] <name>
----

This command displays information on the business group you pass in <name>. +
It will return data such as the owner, the type, subscription information, the entitlements of the group and in which environment is running.
This command does not take any options, except for the default `--help`.

=== business-groups use
[source,bash]
----
$ business-groups use [options] <name>
----

This command makes the business group you specified in <name> active.

=== apps
[source,bash]
----
$ apps [options]
----

This command lists all applications available in your Anypoint-CLI. It returns your application name, its status, the amount of vCores assigned and the last time it was updated. +
This command does not take any options, except for the default `--help`.

=== apps show
[source,bash]
----
$ apps show [options] <name>
----

This command displays information on the application you pass in <name>. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
It will return data such as the application's domain, its status, last time it was updated, the Runtime version, the .zip file name, the region, monitoring and Workers; as well as 'TRUE' or 'FALSE' information for persistent queues and static IPs enablement. +
This command does not take any options, except for the default `--help`.

=== apps json
[source,bash]
----
$ apps json [options] <name>
----

This command returns the raw JSON response of the application you specify in <name>. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== apps stop
[source,bash]
----
$ apps stop [options] <name>
----

This command stops the running application you specify in <name> +
You can start typing your application's name and hit `tab` for Anypoint-ClI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== apps start
[source,bash]
----
$ apps start [options] <name>
----

This command starts the running application you specify in <name> +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== apps restart
[source,bash]
----
$ apps restart [options] <name>
----

This command restarts the running application you specify in <name> +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== apps delete
[source,bash]
----
$ apps delete [options] <name>
----

This command deletes the running application you specify in <name>

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== apps deploy
[source,bash]
----
$ apps deploy [options] <name> <zipfile>
----

This command deploys the Mule deployable archive .zip file that you specify in <zipfile> using the name you set in <name>. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
You will have to provide the absolute or relative path to the deployable zip file in your local hard drive and the name you give to your application has to be unique.

The options this command can take are:
[width="100a",cols="50a,50a",options="header"]
|===
|Option |Description
|--runtime                                   | Name of the runtime environment
|--workers                                      | Number of workers. (This value is '1' by default)
|--workerSize                               | Size of the workers in vCores. (This value is '1' by default)
|--region                                        | Name of the region to deploy to. +
For a list of all supported regions, use the <<regions>> command.
|--property                                    | Set a property (name:value). Can be specified multiple times
|--propertiesFile                        | Overwrite all properties with values from this file. The file format is 1 or more lines in name=value format. Set the absolute path of the properties file in your local hard drive.
|--persistentQueues                   | Enable or disable persistent queues. Can take 'true' or 'false' values. (This value is 'false' by default)
|--persistentQueuesEncrypted  | Enable or disable persistent queue encryption. Can take 'true' or 'false' values. (This value is 'false' by default)
|--staticIPsEnabled                                      | Enable or disable static IPs. Can take 'Enable' or 'Disabled' values. (This value is 'Disabled' by default)
|--autoRestart                            | Automatically restart app when not responding. Can take 'true' or 'false' values. (This value is 'false' by default)
|--help                                                  | output usage information
|===
Note that from Anypoint-CLI you won't be able to allocate static IPs. You can simply enable and disable them.

After typing any option, you can double tap the `tab` key for a full list of all possible options.
For exmaple:
[source,bash]
----
$ deploy <app name> --runtime [tab][tab]
----
Lists all possible runtimes you can select.

[IMPORTANT]
====
If you deploy without using any options, your application will deploy using all your default values.
====

=== apps update
[source,bash]
----
$ apps update [options] <name> [zipfile]
----
This command updates the settings of an existing application. Optionally you can update it by uploading a new .zip file. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass.
This command can take all the same options as the *deploy* option.

You can also start typing your option and hit `tab` for Autocomplete-CLI to autocomplete it for you.

=== apps revert
[source,bash]
----
$ apps revert [options] <name>
----
This command reverts the application defined in <name> to its previous runtime environment. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== apps tail
[source,bash]
----
$ apps tail [options] <name>
----

This command tails application logs. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
This command does not take any options, except for the default `--help`.

=== apps download-logs
[source,bash]
----
$ apps download-logs [options] <name> <directory>
----
This command downloads logs the for application specified in <name> to the specified directory. +
You can start typing your application's name and hit `tab` for Anypoint-CLI to autocomplete it, or you can double tap `tab` for a full list of all the values you can pass. +
Keep in mind that contrarily to what you see in the UI, the logs you download from the CLI won't separate system logs from worker logs.

=== environments
[source,bash]
----
$ environments [options]
----
This command lists all your Environments in your Anypoint Platform. It will return your environment name, its Id and whether it's sandboxed or not. +
This command does not take any options, except for the default `--help`.

=== environments use
[source,bash]
----
$ environments use [options] <name>
----
This command makes active the environment specified in <name>. +
This command does not take any options, except for the default `--help`.

=== environments create
[source,bash]
----
$ environments create [options] <name>
----
This command creates a new environment using the name you set in <name>. +
You can use the `--sandbox` option to create this environment as a sandbox, or use the default `--help`.

=== environments delete
[source,bash]
----
$ environments delete [options] <name>
----
This command deletes the environment specified in <name> +

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== lbs
[source,bash]
----
$ lbs [options]
----
This command lists all load balancers in your Anypoint Platform. It displays load balancer's name, domain, its state and the VPC Id to which the load balancer is bound. +
This command does not take any options, except for the default `--help`.


=== lbs show-rules
[source,bash]
----
$ lbs show-rules [options] <name>
----
This command lists the proxy rules for the load balancer specified in <name>. +
This command does not take any options, except for the default `--help`.

=== lbs add-rule
[source,bash]
----
$ lbs add-rule [options] <name> <index> <inputSubdomain> <inputUri> <appName> <appUri>
----
This command adds a mapping rule to the load balancer specified in <name> at the priority index specified in <index>, using the values set in the variables +
[cols="30a,50a,20a",options="header"]
|===
|Value |Description |Example
|name|Name of the load balancer to which this rule is applied. |testloadbalancer
|index|Priority of the rule.  |1
|inputSubdomain|Name of the sub-domain of your input URL |{app}.api
|inputUri|Name of the URI of your input URL |example.com
|appName|Name of the app of your output URL |{app}-example
|appUri|URI of the app of your output URL |/
|===

For the values in the example above, for an input call to `my-superapp.api.example.com/status?limit=10`, the endpoint `my-superapp-example: /status?limit=10` will be called for the application.


=== lbs delete-rule
[source,bash]
----
$ lbs delete-rule [options] <name> <index>
----
This command deletes the rule at the index specified in <index> from the load balancer specified <name>.

[WARNING]
This command does not prompt twice before deleting. If you send a delete instruction, it does not ask for confirmation.

This command does not take any options, except for the default `--help`.

=== lbs create
[source,bash]
----
$ lbs create [options] <name> <domain> <vpcId> <vpcRegion> <publicKey> <privateKey> <clientCertificate>
----
This command creates a load balancer using the specified values in the variables.
[cols="30a,50a,20a",options="header"]
|===
|Value |Description |Example
| name |Name for the load balancer. | newtestloadbalancer
| domain |Domain of the load balancer. | www.lbtest.com
| vpcId |Id of the VPC to which this load balancer is bound. | vpc-827160e6
| vpcRegion |Region of the VPC to which the load balancer is bound. +
For a list of all supported regions, use the <<regions>> command. | us-east-1
| publicKey |Absolute path to the `.asc` file of your public key in your local hard drive. | /Users/mule/Documents/publicKey.asc
| privateKey |Absolute path to the `.asc` file of your private key in your local hard drive. | /Users/mule/Documents/privateKey.asc
| clientCertificate |Absolute path to the `.pem` file of your certificate in your local hard drive. | /Users/mule/Documents/cert.pem
|===

This command does not take any options, except for the default `--help`.


=== lbs update
[source,bash]
----
$ lbs update [options] <name>
----
This command updates the load balancer specified in <name>. +
The updated values should be passed as options. Check all the options below:
[cols="30a,70a",options="header"]
|===
|Value    			    |Description
|privateKey         |Full path to the updated private key.
|publicKey          |Full path to the updated `.asc` file of your public key.
|clientCertificate  |Full path to the updated `.pem` file certificate.
|domain             |Updated domain.
|help               |Outputs usage information about this command.
|===

=== lbs delete
[source,bash]
----
$ lbs delete [options] <name>
----
This command deletes the load balancer specified in <name>.

=== regions
[source,bash]
----
$ regions [options]
----
This command lists all supported regions. +
This command does not take any options, except for the default `--help`.


=== runtimes
[source,bash]
----
$ runtimes [options]
----
This command lists all supported runtimes. +
This command does not take any options, except for the default `--help`.

=== token
[source,bash]
----
$ token [options]
----
This command returns your API access token. +
This command does not take any options, except for the default `--help`.

=== vpcs
[source,bash]
----
$ vpcs [options]
----
This command lists all available VPCs. It returns ID, region, and environment of the network and wether it is the default VPC or not.

=== exit
[source,bash]
----
$ exit [options]
----
This command exits Anypoint-CLI. +
This command does not take any options, except for the default `--help`
